#server:
#  port: 8080

spring:
  profiles:
    default: dev

#  datasource: # ?? ?? application ?? ?? ??. ??? ?? ??.
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/test
#    username: dongeon110
#    password: 1234

#mybatis:
#  type-aliases-package: com.note
#  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true # DB CAMEL_CASE -> Java snakeCase ?? ??
#    jdbc-type-for-null: varchar
#    call-setters-on-nulls: true # HashMap ? ? ?? Null ? ??
#
#logging:
#  level:
#    root: info